### ISSUE TITLE
Server closed the connection unexpectedly

### ISSUE THREAD

**Issue by minsau** [Opus10/django-pgpubsub#22]
Hello I am trying to integrate the library into my project and I haven't had success, this is a minimized example of my docker compose configuration

```
version: "3.7"
services:
  core:
    entrypoint: run.py
    container_name: core
    ports:
      - "8000:8000"
    image: Core
    build:
      dockerfile: "${DOCKERFILE}"
      context: .
      target: "${TARGET}"
    volumes:
      - "./:/core"
    environment:
      ...
    depends_on:
      - postgres
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
  celery_worker:
    entrypoint: sh scripts/deploy/celery.sh
    container_name: celery_worker
    ports:
      - "5001:8000"
    depends_on:
      - core
      - redis
    image: celery_worker
  flower:
    image: "mher/flower"
    container_name: celery_flower
    ports:
      - "5555:5555"
  postgres:
    image: "postgres:13.2-alpine"
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
```

And when I execute next command, throws an error:
```
docker exec core python manage.py listen
Listening on api.channels.series.SeriesChannel
Process pgpubsub_process_0:
Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
psycopg2.OperationalError: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/venv/lib/python3.8/site-packages/pgpubsub/listen.py", line 25, in listen
    pg_connection = listen_to_channels(channels)
  File "/opt/venv/lib/python3.8/site-packages/pgpubsub/listen.py", line 62, in listen_to_channels
    cursor.execute(f'LISTEN {channel.listen_safe_name()};')
  File "/opt/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/opt/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
django.db.utils.OperationalError: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
```

I was thinking in something related with the postgres version but I tested with a host postgres, other postgres image (no alpine) and with Amazon RDS (here shows an SSL error) and without luck

I tested in ubuntu server 64 bits and in a Mac M1

**Comment by PaulGilmartin** [comment]
@minsau After a bit of digging, it seems like one can run into this issue if we do not close the database connection before forking a child process (see https://stackoverflow.com/questions/8242837/django-multiprocessing-and-database-connections/10684672#10684672 for example).

I have updated [this](https://github.com/Opus10/django-pgpubsub/tree/windows_multiprocess_test) branch so that we do actually close database connections before forking. Could you pull in that branch and check if it fixes your issue at all?

@ricardoduarte if you get a chance to test this branch at some point that would also be great :)

**Comment by ricardoduarte** [comment]
Hello @PaulGilmartin 

It seems a good solution, can't do it today, but will definitely try it later.

**Comment by minsau** [comment]
Sorry I a, really new with this packages, how can integrate that specific branch to my project?

**Comment by minsau** [comment]
Hello! It worked :D 
```
docker exec core python manage.py listen
Listening on api.channels.series.SeriesChannel
Listening for notifications...
```

**Comment by PaulGilmartin** [comment]
@minsau Great! I still find it strange that I could never reproduce it, but I'll leave that as a mystery for now.
I will try to make a proper release later tonight. I'll let you know when it's on pypi.

**Comment by PaulGilmartin** [comment]
@minsau (@ricardoduarte ) You can find the fix in version 1.0.2 https://pypi.org/project/django-pgpubsub/1.0.2/.

@minsau Out of curiosity, what are you using django-pgpubsub for :) ?

**Comment by minsau** [comment]
Thanks a lot!
I am using it integrated with django triggers to keep updated a field in a table! Its awesome !

**Comment by ricardoduarte** [comment]
@PaulGilmartin Just tested it again and it is working flawlessly. Awesome! Thank you so much 😄

**Comment by PaulGilmartin** [comment]
@ricardoduarte Great! Thanks for testing again
