### ISSUE TITLE
Cannot remove and can't get rid of manage.py migrate errors: TypeError: 'class Meta' got invalid attribute(s): triggers

### ISSUE THREAD

**Issue by metalaureate** [Opus10/django-pgpubsub#25]
HI there! I needed to remove this package from a project that does not use it, but am in now in some kind of hell that I can't get out of unless I keep the packages installed

I uninstalled `django-pgpubsub==1.0.1` and removed the settings reference,  but now get this error when i try to manage.py migrate:

```
 Apply all migrations: admin, auth, contenttypes, django_q, mirror, sessions
Traceback (most recent call last):
  File "/Users/sjhill/Documents/yat/projects/mm/api/./manage.py", line 21, in <module>
    main()
  File "/Users/sjhill/Documents/yat/projects/mm/api/./manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/Users/sjhill/opt/anaconda3/envs/mm/lib/python3.9/site-packages/django/core/management/__init__.py", line 425, in execute_from_command_line
    utility.execute()
  File "/Users/sjhill/opt/anaconda3/envs/mm/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/sjhill/opt/anaconda3/envs/mm/lib/python3.9/site-packages/django/core/management/base.py", line 373, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/sjhill/opt/anaconda3/envs/mm/lib/python3.9/site-packages/django/core/management/base.py", line 417, in execute
    output = self.handle(*args, **options)
  File "/Users/sjhill/opt/anaconda3/envs/mm/lib/python3.9/site-packages/django/core/management/base.py", line 90, in wrapped
    res = handle_func(*args, **kwargs)
  File "/Users/sjhill/opt/anaconda3/envs/mm/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 211, in handle
    pre_migrate_apps = pre_migrate_state.apps
  File "/Users/sjhill/opt/anaconda3/envs/mm/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/sjhill/opt/anaconda3/envs/mm/lib/python3.9/site-packages/django/db/migrations/state.py", line 505, in apps
    return StateApps(self.real_apps, self.models)
  File "/Users/sjhill/opt/anaconda3/envs/mm/lib/python3.9/site-packages/django/db/migrations/state.py", line 562, in __init__
    self.render_multiple([*models.values(), *self.real_models])
  File "/Users/sjhill/opt/anaconda3/envs/mm/lib/python3.9/site-packages/django/db/migrations/state.py", line 597, in render_multiple
    model.render(self)
  File "/Users/sjhill/opt/anaconda3/envs/mm/lib/python3.9/site-packages/django/db/migrations/state.py", line 872, in render
    return type(self.name, bases, body)
  File "/Users/sjhill/opt/anaconda3/envs/mm/lib/python3.9/site-packages/django/db/models/base.py", line 122, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/Users/sjhill/opt/anaconda3/envs/mm/lib/python3.9/site-packages/django/db/models/base.py", line 326, in add_to_class
    value.contribute_to_class(cls, name)
  File "/Users/sjhill/opt/anaconda3/envs/mm/lib/python3.9/site-packages/django/db/models/options.py", line 199, in contribute_to_class
    raise TypeError("'class Meta' got invalid attribute(s): %s" % ','.join(meta_attrs))
TypeError: 'class Meta' got invalid attribute(s): triggers
```

I still get this error even when I re-install the package. It only goes away if I add pgtrigger back into the Django app. Hoping you can help me!

**Comment by PaulGilmartin** [comment]
Hey @metalaureate , not had the chance to check this out yet as I just got back from a holiday abroad. I'll try to make some time for it this week :)

**Comment by metalaureate** [comment]
hi Nice. No worries, not urgent. I left it in for now. I think my problem comes down to, is it safe to delete Django migrations I'm never going to run that contain dependencies I want to remove. Diddling with Migration files is a path that always leads me to hell. I don't get why they have to contain import dependencies to things that might be removed at a later date.

**Comment by PaulGilmartin** [comment]
@metalaureate Hmm yeah it does strike me as an issue which isn't directly related to django-pgpubsub (but I could be wrong).
 Before uninstalling django-pgpubsub, did you try rolling back the migrations applied by django-pgpubsub? I would say that's a good idea to start with, since if you don't have the package anymore, you should get rid of the database tables/triggers it created.

I do see what you mean about deleting the migration file though. Here's a potential idea you could try. I haven't tested this, but if I wanted to uninstall I would

1. Clean up any Notification objects left.
2. Rollback the migration which created the Notification table and any which created any triggers.
3. Try squashing the original migration together with the no-op migration - maybe that makes Django just get rid of the migration file in a safe way?
4. If (3) works, you can then remove the dependency. If it doesn't, you may need to manually delete the pgpubsub migration files and/or do some sort of fake migration effort.


 It seems like this would be a general issue for any third party package you want to get rid of that creates its own migrations. There's surely some docs about this online somewhere, but I'm not sure where unfortunately

**Comment by metalaureate** [comment]
Thank you these are great suggestions.
